#!/bin/bash
#
# Usage: install-via-ssh user@12.34.56.78
#
# Installs hcproxy as systemd service on the specified remote machine. The user must have
# sudo privileges without password.

set -euE
set -o pipefail

if [[ $# -ne 1 ]]; then
  echo 'Usage: install-via-ssh user@12.34.56.78' >&2
  exit 1
fi

readonly host=$1

dir=$(dirname ${BASH_SOURCE[@]})
cd -- "$dir"

echo "Compiling hcproxy..." >&2
make -j 8

echo "Copying hcproxy to $host..." >&2
scp -o "StrictHostKeyChecking no" hcproxy hcproxy.service "$host":~

echo "Installing hcproxy on $host..." >&2
ssh -o "StrictHostKeyChecking no" "$host" 'bash -ex' <<END
  sudo cp -f hcproxy /usr/sbin/
  sudo cp -f hcproxy.service /lib/systemd/system/
  sudo systemd-analyze verify /lib/systemd/system/hcproxy.service
  sudo systemctl stop hcproxy 2>/dev/null || true
  sudo systemctl disable hcproxy 2>/dev/null || true
  sudo systemctl enable --now hcproxy
  rm hcproxy hcproxy.service
END

echo "SUCCESS: installed hcproxy on $host" >&2
